[package]
name = "blog"
version = "0.1.0"
edition = "2021"
authors = [ "Joe <joe.gloach@gmail.com>" ]

[package.metadata.release]
release = false

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
axum = { version = "0.8.3", default-features = false, features = ["macros", "query"] }
axum-htmx = "0.7.0"
axum-extra = { version = "0.10.1", default-features = false, features = ["typed-header"] }
worker = { version="0.5.0", features=["http", "axum"] }
tower-service = "0.3.2"
tower-http = { version = "0.6.2", features = ["cors"] }
console_error_panic_hook = { version = "0.1.1" }
serde = { version = "1.0", features = ["derive"] }
maud = { version = "0.27.0", features = ["axum"] }
iconify = "0.3.1"
chrono = { version = "0.4.40", default-features = false, features = ["std"] }
# blog generation
glob = "0.3.2"
pulldown-cmark = { version = "0.13.0" }
matter = { version = "0.1.0-alpha4" }
yaml-rust = "0.4"
